"""
data/prepare_data.py — Download, Tokenize, and Save Pre-Training Data.

Builds train.bin and val.bin — the binary token files read by the training loop.
Run this after tokenizer/train_tokenizer.py completes.

Token target: 7B tokens (Chinchilla-optimal for 350M model: 20 × 350M = 7B)

Data mix (70% code | 20% English | 10% SE conversations):
  CODE (70%):
    - bigcode/the-stack         ← actual code files, 16 languages (needs HF token)
    - ise-uiuc/Magicoder-OSS-75K     ← SE problems + solutions
    - theblackcat102/evol-codealpaca  ← complex coding tasks
    - m-a-p/CodeFeedback              ← code review + bug fixing

  ENGLISH (20%):
    - HuggingFaceFW/fineweb-edu      ← educational web text, planning/explaining

  SE CONVERSATIONS (10%):
    - teknium/OpenHermes-2.5         ← multi-turn coding + general discussions

HF Token required for the-stack-smol:
  1. huggingface.co/settings/tokens → create Read token
  2. Accept terms: huggingface.co/datasets/bigcode/the-stack
  3. Add to .env:  HF_TOKEN=hf_xxxxxxxxxxxx
     OR set env:   $env:HF_TOKEN = "hf_xxxxxxxxxxxx"

Output:
    data/processed/train.bin   (uint16 flat token IDs, ~14 GB)
    data/processed/val.bin     (~200 MB)

Usage:
    python data/prepare_data.py
    python data/prepare_data.py --max-tokens 1000000000   # 1B quick test
"""

import os
import sys
import time
import argparse
import numpy as np
from typing import Iterator

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Suppress Windows symlink warning from HuggingFace (cache still works fine)
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")


# ── Load HF token from .env if present ────────────────────────────────────────

def _load_hf_token() -> None:
    """Load HF_TOKEN from .env file into environment (if not already set)."""
    if os.environ.get("HF_TOKEN"):
        return  # Already set

    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
    if not os.path.exists(env_path):
        return

    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("HF_TOKEN="):
                token = line.split("=", 1)[1].strip().strip('"').strip("'")
                if token:
                    os.environ["HF_TOKEN"] = token
                    print(f"  HF_TOKEN loaded from .env ✓")
                    return

_load_hf_token()


# ── Configuration ──────────────────────────────────────────────────────────────

# Chinchilla optimal for 350M: 20 × 350M = 7B tokens
TARGET_TRAIN_TOKENS = 7_000_000_000
TARGET_VAL_TOKENS   =   100_000_000   # 100M tokens

# Mix ratios
CODE_RATIO    = 0.60   # 60% code
ENGLISH_RATIO = 0.15   # 15% natural English
SECONV_RATIO  = 0.10   # 10% SE conversations
SEKNOW_RATIO  = 0.15   # 15% SE knowledge (system design, security, DevOps, etc.)

# All SE-relevant languages available in bigcode/the-stack
# Languages not found in the dataset are automatically skipped (try/except)
STACK_LANGUAGES = [
    # ── Systems / Low-level ───────────────────────────────
    "c", "c++", "rust", "assembly", "cuda",

    # ── General purpose ───────────────────────────────────
    "python", "java", "go", "kotlin", "scala",
    "swift", "dart", "r", "julia", "haskell",
    "ocaml", "elixir", "erlang", "clojure",

    # ── Scripting / Shell ─────────────────────────────────
    "javascript", "typescript", "ruby", "php", "perl",
    "lua", "shell", "powershell", "batchfile",

    # ── Web ───────────────────────────────────────────────
    "html", "css", "vue",

    # ── Data / Query ──────────────────────────────────────
    "sql",

    # ── DevOps / Config ───────────────────────────────────
    "dockerfile", "makefile", "cmake",

    # ── .NET ──────────────────────────────────────────────
    "c-sharp",

    # ── Functional ────────────────────────────────────────
    "f#", "zig",
]


# ── Quality filter ─────────────────────────────────────────────────────────────

def is_quality_code(content: str) -> bool:
    """Return True if the code passes basic quality checks."""
    if not content:
        return False
    length = len(content)
    if length < 100 or length > 500_000:
        return False
    lines = content.split("\n")
    if lines and length / len(lines) > 400:
        return False   # Minified
    ascii_ratio = sum(1 for c in content if ord(c) < 128) / length
    if ascii_ratio < 0.80:
        return False   # Binary / non-code
    first_500 = content[:500].lower()
    for marker in ["auto-generated", "do not edit", "generated by", "this file is generated"]:
        if marker in first_500:
            return False
    return True


# ── Data streaming ─────────────────────────────────────────────────────────────

def stream_the_stack(char_budget_per_lang: int) -> Iterator[str]:
    """
    Stream actual code files from bigcode/the-stack (full).
    Best quality — filtered, deduplicated, permissive licenses only.
    Requires HF_TOKEN + accepted terms: huggingface.co/datasets/bigcode/the-stack
    """
    from datasets import load_dataset
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        print("  [the-stack] No HF_TOKEN set — skipping gated dataset")
        return

    print(f"  [the-stack] Streaming {len(STACK_LANGUAGES)} languages...", flush=True)
    for lang in STACK_LANGUAGES:
        lang_chars = 0
        try:
            ds = load_dataset(
                "bigcode/the-stack",
                data_dir=f"data/{lang}",
                split="train",
                streaming=True,
                token=hf_token,
            )
            for sample in ds:
                if lang_chars >= char_budget_per_lang:
                    break
                content = sample.get("content", "") or ""
                if not is_quality_code(content):
                    continue
                yield content
                lang_chars += len(content)
            print(f"    → {lang}: {lang_chars / 1e9:.2f}B chars")
        except Exception as e:
            print(f"    Warning {lang}: {e}")


def stream_magicoder(char_budget: int) -> Iterator[str]:
    """Stream Magicoder-OSS-Instruct-75K — SE problems + solutions."""
    from datasets import load_dataset
    print("  [Magicoder-OSS-Instruct] streaming...", flush=True)
    chars = 0
    try:
        ds = load_dataset("ise-uiuc/Magicoder-OSS-Instruct-75K", split="train", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            text = f"{sample.get('problem','')}\n\n{sample.get('solution','')}".strip()
            if len(text) < 50: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e6:.1f}M chars")
    except Exception as e:
        print(f"    Warning: {e}")


def stream_evol_instruct(char_budget: int) -> Iterator[str]:
    """Stream evol-codealpaca-v1 — complex coding tasks."""
    from datasets import load_dataset
    print("  [evol-codealpaca-v1] streaming...", flush=True)
    chars = 0
    try:
        ds = load_dataset("theblackcat102/evol-codealpaca-v1", split="train", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            text = f"{sample.get('instruction','')}\n\n{sample.get('output','')}".strip()
            if len(text) < 50: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e6:.1f}M chars")
    except Exception as e:
        print(f"    Warning: {e}")


def stream_taco(char_budget: int) -> Iterator[str]:
    """
    Stream BAAI/TACO — competitive programming problems + solutions.
    26K problems, each with multiple accepted solutions.
    Teaches algorithms, data structures, problem-solving patterns.
    """
    import json
    from datasets import load_dataset
    print("  [BAAI/TACO] competitive programming...", flush=True)
    chars = 0
    try:
        ds = load_dataset("BAAI/TACO", split="train", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            question  = sample.get("question", "") or ""
            solutions = sample.get("solutions", "[]") or "[]"
            # solutions is a JSON string containing list of code strings
            try:
                sol_list = json.loads(solutions)
            except Exception:
                sol_list = []
            for sol in sol_list:
                if chars >= char_budget: break
                if not sol or len(sol) < 50: continue
                text = f"{question}\n\n{sol}".strip()
                yield text
                chars += len(text)
        print(f"    → {chars / 1e6:.1f}M chars")
    except Exception as e:
        print(f"    Warning [TACO]: {e}")


def stream_codefeedback(char_budget: int) -> Iterator[str]:
    """Stream CodeFeedback — code review, debugging, explanations."""
    from datasets import load_dataset
    print("  [CodeFeedback-Filtered-Instruction] streaming...", flush=True)
    chars = 0
    try:
        ds = load_dataset("m-a-p/CodeFeedback-Filtered-Instruction", split="train", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            text = f"{sample.get('query','')}\n\n{sample.get('answer','')}".strip()
            if len(text) < 50: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e6:.1f}M chars")
    except Exception as e:
        print(f"    Warning: {e}")


def stream_fineweb_edu(char_budget: int) -> Iterator[str]:
    """Stream fineweb-edu — high quality English educational text."""
    from datasets import load_dataset
    print("  [fineweb-edu] streaming...", flush=True)
    chars = 0
    try:
        ds = load_dataset(
            "HuggingFaceFW/fineweb-edu",
            name="sample-10BT",
            split="train",
            streaming=True,
        )
        for sample in ds:
            if chars >= char_budget: break
            text = sample.get("text", "") or ""
            if len(text) < 100 or len(text) > 50_000: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e9:.2f}B chars")
    except Exception as e:
        print(f"    Warning: {e}")


def stream_stack_exchange(char_budget: int) -> Iterator[str]:
    """
    Stream ArmelR/stack-exchange-instruction — Q&A from ALL Stack Exchange sites.

    Covers ALL software engineering knowledge domains:
      - Stack Overflow       → coding, algorithms, data structures
      - Security             → cybersecurity, pen testing, OWASP
      - Server Fault         → DevOps, Linux, networking, cloud
      - Software Engineering → architecture, SOLID, design patterns
      - Database Admins      → DB design, query optimization, indexing
      - Code Review          → best practices, clean code
      - Unix/Linux           → systems, shell, scripting
      - and 100+ more sites
    """
    from datasets import load_dataset
    print("  [stack-exchange-instruction] streaming all SE domains...", flush=True)
    chars = 0
    try:
        ds = load_dataset("ArmelR/stack-exchange-instruction", split="test", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            question = sample.get("question", "") or ""
            response = sample.get("response", "") or ""
            text     = f"{question}\n\n{response}".strip()
            if len(text) < 100: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e9:.2f}B chars")
    except Exception as e:
        print(f"    Warning: {e}")


def stream_openhermes(char_budget: int) -> Iterator[str]:
    """Stream OpenHermes-2.5 — diverse SE conversations and coding Q&A."""
    from datasets import load_dataset
    print("  [teknium/OpenHermes-2.5] streaming...", flush=True)
    chars = 0
    try:
        ds = load_dataset("teknium/OpenHermes-2.5", split="train", streaming=True)
        for sample in ds:
            if chars >= char_budget: break
            conversations = sample.get("conversations", [])
            text = "\n".join(c.get("value", "") for c in conversations).strip()
            if len(text) < 100: continue
            yield text
            chars += len(text)
        print(f"    → {chars / 1e9:.2f}B chars")
    except Exception as e:
        print(f"    Warning: {e}")


# ── Tokenization + binary writing ──────────────────────────────────────────────

def tokenize_and_write(
    text_iterator: Iterator[str],
    tokenizer,
    output_path: str,
    target_tokens: int,
    eos_token_id: int = 1,
    report_every: int = 100_000_000,
    start_tokens: int = 0,
) -> int:
    """
    Tokenize a stream of text and write as flat uint16 binary file.
    EOS token is appended between every document.
    Supports resuming from existing binary file if start_tokens > 0.
    Returns total tokens written / in file.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    mode = "ab" if (start_tokens > 0 and os.path.exists(output_path)) else "wb"

    total_tokens = start_tokens
    total_docs   = 0
    buffer       = []
    FLUSH_SIZE   = 100_000
    last_report  = start_tokens
    t_start      = time.time()

    # Fast skip if resuming
    chars_to_skip = start_tokens * 4  # Average ~4 chars per token
    skipped_chars = 0
    if start_tokens > 0:
        print(f"Resuming {output_path}: fast-skipping ~{chars_to_skip/1e9:.2f}B chars (~{start_tokens/1e9:.3f}B tokens)...")

    print(f"\nWriting ({mode}) → {output_path}")
    print(f"Target:    {target_tokens / 1e9:.2f}B tokens (starting at {total_tokens / 1e9:.3f}B)\n")

    with open(output_path, mode) as f:
        for text in text_iterator:
            if total_tokens >= target_tokens:
                break

            if skipped_chars < chars_to_skip:
                skipped_chars += len(text)
                if skipped_chars % 2_000_000_000 < len(text):
                    print(f"  Fast-forwarding stream... {skipped_chars/1e9:.2f}B / {chars_to_skip/1e9:.2f}B chars skipped", flush=True)
                continue

            try:
                ids = tokenizer.encode(text).ids
            except Exception:
                continue
            if not ids:
                continue

            ids.append(eos_token_id)
            buffer.extend(ids)
            total_tokens += len(ids)
            total_docs   += 1

            if len(buffer) >= FLUSH_SIZE:
                np.array(buffer[:FLUSH_SIZE], dtype=np.uint16).tofile(f)
                buffer = buffer[FLUSH_SIZE:]

            if total_tokens - last_report >= report_every:
                elapsed = time.time() - t_start
                tok_sec = (total_tokens - start_tokens) / max(elapsed, 1)
                pct     = 100 * total_tokens / target_tokens
                rem_tok = target_tokens - total_tokens
                eta_h   = rem_tok / max(tok_sec, 1) / 3600 if tok_sec > 0 else 0
                print(
                    f"  {total_tokens/1e9:.3f}B / {target_tokens/1e9:.1f}B "
                    f"({pct:.1f}%) | {tok_sec/1000:.1f}K tok/sec | "
                    f"ETA {eta_h:.1f}h | docs: {total_docs:,}"
                )
                last_report = total_tokens

        if buffer:
            np.array(buffer, dtype=np.uint16).tofile(f)

    size_gb = os.path.getsize(output_path) / 1e9
    elapsed = time.time() - t_start
    print(f"\n  Done: {total_tokens:,} tokens | {size_gb:.2f} GB | {elapsed/3600:.1f}h")
    return total_tokens


# ── Main ───────────────────────────────────────────────────────────────────────

def prepare_data(max_train_tokens: int, output_dir: str) -> None:
    """Run the full data preparation pipeline."""
    has_token = bool(os.environ.get("HF_TOKEN"))

    print(f"\n{'='*65}")
    print(f"  SE-LLM-350M Data Preparation Pipeline")
    print(f"  Train target: {max_train_tokens / 1e9:.1f}B tokens  "
          f"(Chinchilla-optimal for 350M)")
    print(f"  Val target:   {TARGET_VAL_TOKENS / 1e6:.0f}M tokens")
    print(f"  Mix:          70% code | 20% English | 10% SE conversations")
    print(f"  HF Token:     {'✅ set — gated datasets unlocked' if has_token else '❌ not set — the-stack-smol will be skipped'}")
    print(f"  Output dir:   {output_dir}/")
    print(f"{'='*65}\n")

    # ── Load tokenizer ────────────────────────────────────────────
    tok_path = "tokenizer/tokenizer.json"
    if not os.path.exists(tok_path):
        raise FileNotFoundError(
            f"Tokenizer not found: {tok_path}\n"
            f"Run first: python tokenizer/train_tokenizer.py"
        )
    from tokenizers import Tokenizer
    tokenizer    = Tokenizer.from_file(tok_path)
    eos_token_id = tokenizer.token_to_id("<|endoftext|>") or 1
    print(f"Tokenizer: vocab={tokenizer.get_vocab_size():,} | EOS={eos_token_id}\n")

    total_chars    = max_train_tokens * 4   # ~4 chars per token
    code_budget    = int(total_chars * CODE_RATIO)
    english_budget = int(total_chars * ENGLISH_RATIO)
    seconv_budget  = int(total_chars * SECONV_RATIO)
    seknow_budget  = int(total_chars * SEKNOW_RATIO)

    # Character budgets scaled to guarantee reaching full 7.0B tokens (~35B chars)
    stack_per_lang  = 600_000_000       # 600M chars/lang × 38 languages ≈ 22.8B chars (~5.7B tokens)
    instruct_budget = 1_000_000_000     # 1.0B chars per instruction dataset
    english_budget  = 12_000_000_000    # 12.0B chars (~3.0B tokens) from FineWeb-Edu
    seconv_budget   = 5_000_000_000     # 5.0B chars (~1.25B tokens) from Q&A / Conversations

    # ── TRAINING DATA ─────────────────────────────────────────────
    train_path = os.path.join(output_dir, "train.bin")
    start_train_tokens = 0
    if os.path.exists(train_path):
        size = os.path.getsize(train_path)
        if size % 2 != 0:
            size -= 1
            with open(train_path, "r+b") as f:
                f.truncate(size)
        existing_tokens = size // 2
        if existing_tokens >= max_train_tokens:
            print(f"train.bin complete ({size/1e9:.2f} GB, {existing_tokens/1e9:.3f}B tokens) — skipping.\n")
            start_train_tokens = existing_tokens
        else:
            print(f"train.bin partial ({size/1e9:.2f} GB, {existing_tokens/1e9:.3f}B tokens) — RESUMING to {max_train_tokens/1e9:.1f}B tokens...\n")
            start_train_tokens = existing_tokens

    if start_train_tokens < max_train_tokens:
        print("--- Building / Resuming TRAIN set ---")
        print(f"  Target:          {max_train_tokens/1e9:.1f}B tokens")
        print(f"  Code budget:     {stack_per_lang*len(STACK_LANGUAGES)/1e9:.1f}B chars (Stack)")
        print(f"  English budget:  {english_budget/1e9:.1f}B chars (FineWeb-Edu)\n")

        def all_train_data():
            # ── CODE (70%) ────────────────────────────────────────
            print("\n── CODE ─────────────────────────────────────────────────")
            yield from stream_the_stack(stack_per_lang)
            yield from stream_magicoder(instruct_budget)
            yield from stream_evol_instruct(instruct_budget)
            yield from stream_codefeedback(instruct_budget)
            # ── ENGLISH & SE KNOWLEDGE (30%) ──────────────────────
            print("\n── ENGLISH & SE KNOWLEDGE ──────────────────────────────")
            yield from stream_fineweb_edu(english_budget)
            yield from stream_stack_exchange(seconv_budget)
            yield from stream_openhermes(seconv_budget)
            # ── FILL GAP (Guarantees reaching 7.0B tokens) ────────
            print("\n── FILLING REMAINING GAP TO 7.0B TOKENS ────────────────")
            yield from stream_fineweb_edu(20_000_000_000)

        train_tokens = tokenize_and_write(
            all_train_data(), tokenizer, train_path,
            target_tokens=max_train_tokens, eos_token_id=eos_token_id,
            start_tokens=start_train_tokens,
        )
        print(f"\nTRAIN: {train_tokens/1e9:.3f}B tokens → {train_path}")

    # ── VALIDATION DATA ───────────────────────────────────────────
    val_path = os.path.join(output_dir, "val.bin")
    start_val_tokens = 0
    if os.path.exists(val_path):
        size = os.path.getsize(val_path)
        if size % 2 != 0:
            size -= 1
            with open(val_path, "r+b") as f:
                f.truncate(size)
        existing_tokens = size // 2
        if existing_tokens >= TARGET_VAL_TOKENS:
            print(f"val.bin complete ({size/1e6:.1f} MB, {existing_tokens/1e6:.1f}M tokens) — skipping.\n")
            start_val_tokens = existing_tokens
        else:
            print(f"val.bin partial ({size/1e6:.1f} MB, {existing_tokens/1e6:.1f}M tokens) — RESUMING...\n")
            start_val_tokens = existing_tokens

    if start_val_tokens < TARGET_VAL_TOKENS:
        print("\n--- Building / Resuming VAL set ---")

        def val_data():
            yield from stream_magicoder(TARGET_VAL_TOKENS * 4 // 2)
            yield from stream_fineweb_edu(TARGET_VAL_TOKENS * 4 // 2)

        val_tokens = tokenize_and_write(
            val_data(), tokenizer, val_path,
            target_tokens=TARGET_VAL_TOKENS, eos_token_id=eos_token_id,
            start_tokens=start_val_tokens,
        )
        print(f"VAL: {val_tokens/1e6:.1f}M tokens → {val_path}")

    # ── Summary ───────────────────────────────────────────────────
    print(f"\n{'='*65}")
    print(f"  Data Preparation COMPLETE")
    for fname in ["train.bin", "val.bin"]:
        fpath = os.path.join(output_dir, fname)
        if os.path.exists(fpath):
            n_tokens = os.path.getsize(fpath) // 2
            size_gb  = os.path.getsize(fpath) / 1e9
            print(f"  {fname:<12} {n_tokens/1e9:.3f}B tokens | {size_gb:.2f} GB")
    print(f"\n  Upload to Kaggle:")
    print(f"    1. {output_dir}/train.bin  (~14 GB)")
    print(f"    2. {output_dir}/val.bin")
    print(f"    3. tokenizer/tokenizer.json")
    print(f"{'='*65}\n")


# ── Entry point ────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare SE-LLM-350M pre-training data")
    parser.add_argument("--max-tokens", type=int, default=TARGET_TRAIN_TOKENS,
                        help=f"Train token target (default: {TARGET_TRAIN_TOKENS:,})")
    parser.add_argument("--output-dir", type=str, default="data/processed",
                        help="Output directory (default: data/processed)")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    prepare_data(args.max_tokens, args.output_dir)
